server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /api/users/ {
        rewrite ^/api/users/(.*)$ /users/$1 break;
        proxy_pass http://user:9001;
    }

    location /api/products/ {
        rewrite ^/api/products/(.*)$ /products/$1 break;
        proxy_pass http://product:9003;
    }

    location /api/filter/ {
        rewrite ^/api/filter/(.*)$ /filter/$1 break;
        proxy_pass http://product:9003;
    }

    location /api/cart/ {
        rewrite ^/api/cart/(.*)$ /cart/$1 break;
        proxy_pass http://cart:9002;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
