apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: game-stora-observability
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Bharatdwaj3/refine-devops.git
    targetRevision: main
    path: k8s/observability
  destination:
    server: https://kubernetes.default.svc
    namespace: game-stora
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true