apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: user
  name: user
spec:
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {duration: 30s}
      - setWeight: 40
      - pause: {duration: 30s}
      - setWeight: 60
      - pause: {duration: 30s}
      - setWeight: 80
      - pause: {duration: 30s}
      - setWeight: 100
  replicas: 3
  progressDeadlineSeconds: 120
  selector:
    matchLabels:
      io.kompose.service: user
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/lrn-k86-default: "true"
        io.kompose.service: user



    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - args:
            - node
            - server.js
          image: game-stora-user
          imagePullPolicy: Always
          name: user
          ports:
            - containerPort: 3001
              protocol: TCP
          resources: {}
          readinessProbe:
            tcpSocket:
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3

          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: MONGO_USERNAME
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: MONGO_PASSWORD
            - name: MONGO_CLUSTER
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: MONGO_CLUSTER
            - name: MONGO_DBNAME
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: MONGO_DBNAME
            - name: ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: ACCESS_TOKEN
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: user-secrets
                  key: PORT
      restartPolicy: Always
status: {}
