namespace: game-stora

resources:
  - deployment/user-rollout.yaml
  - deployment/product-rollout.yaml
  - deployment/cart-rollout.yaml
  - deployment/frontend-rollout.yaml
  - deployment/db-deployment.yaml
  - deployment/mongo-data-persistentvolumeclaim.yaml
  - service/user-service.yaml
  - service/product-service.yaml
  - service/cart-service.yaml
  - service/frontend-service.yaml
  - service/db-service.yaml
  - frontend-nginx-config.yaml

images:
  - name: game-stora-user
    newName: ghcr.io/bharatdwaj3/refine-devops/user
    newTag: 0efd7ea
  - name: game-stora-product
    newName: ghcr.io/bharatdwaj3/refine-devops/product
    newTag: 0efd7ea
  - name: game-stora-cart
    newName: ghcr.io/bharatdwaj3/refine-devops/cart
    newTag: 0efd7ea
  - name: game-stora-frontend
    newName: ghcr.io/bharatdwaj3/refine-devops/frontend
    newTag: 0efd7ea
