apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: front-end
  name: front-end
spec:
  type: NodePort
  ports:
    - name: "80"
      port: 80
      targetPort: 80
      nodePort: 30004
  selector:
    io.kompose.service: front-end
status:
  loadBalancer: {}
