apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: game-stora
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        index index.html;

        location /api/users/ {
            rewrite ^/api/users/(.*)$ /users/$1 break;
            proxy_pass http://user.ecommerce.svc.cluster.local:9001;
        }

        location /api/products/ {
            rewrite ^/api/products/(.*)$ /products/$1 break;
            proxy_pass http://product.ecommerce.svc.cluster.local:9003;
        }

        location /api/filter/ {
            rewrite ^/api/filter/(.*)$ /filter/$1 break;
            proxy_pass http://product.ecommerce.svc.cluster.local:9003;
        }

        location /api/cart/ {
            rewrite ^/api/cart/(.*)$ /cart/$1 break;
            proxy_pass http://cart.ecommerce.svc.cluster.local:9002;
        }

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
